window.QUIZ_DATA = [
  {
    "id": 1,
    "topic": "1BP404",
    "question": "Na kterém trhu získává emitent nové peníze?",
    "option_a": "Na primárním trhu",
    "option_b": "Na sekundárním burzovním trhu",
    "option_c": "Na sekundárním mimoburzovním (OTC) trhu",
    "option_d": "Na peněžním trhu při obchodu s už vydanými poukázkami",
    "correct": "A",
    "explanation": "Emitent dostává peníze jen při prvním prodeji cenného papíru, tedy na primárním trhu (emise, IPO). Na sekundárním trhu obchodují investoři mezi sebou a emitent nedostane nic.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 1
  },
  {
    "id": 2,
    "topic": "1BP404",
    "question": "Hranice mezi peněžním a kapitálovým trhem je určena:",
    "option_a": "druhem instrumentu (akcie × dluhopis)",
    "option_b": "splatností instrumentu 1 rok",
    "option_c": "tím, zda se obchoduje na burze",
    "option_d": "osobou emitenta (stát × firma)",
    "correct": "B",
    "explanation": "Peněžní trh = instrumenty se splatností do 1 roku, kapitálový trh = nad 1 rok. Akcie nemá splatnost, ale patří na kapitálový trh.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 1
  },
  {
    "id": 3,
    "topic": "1BP404",
    "question": "Kapitálový trh se podle běžného členění skládá z:",
    "option_a": "trhu dlouhodobých úvěrů a trhu cenných papírů",
    "option_b": "devizového trhu a trhu drahých kovů",
    "option_c": "peněžního trhu a trhu derivátů",
    "option_d": "primárního trhu a trhu pokladničních poukázek",
    "correct": "A",
    "explanation": "Kapitálový trh = trh dlouhodobých úvěrů + trh cenných papírů. Devizový trh a trh drahých kovů jsou samostatné části finančního trhu.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 1
  },
  {
    "id": 4,
    "topic": "1BP404",
    "question": "Který znak odpovídá bankovnímu (kontinentálnímu) modelu alokace úspor?",
    "option_a": "Kontrola managementu firem hlavně přes hrozbu nepřátelského převzetí",
    "option_b": "Dominance penzijních fondů a akcií v úsporách domácností",
    "option_c": "Úspory plynou hlavně přes vklady do bankovních úvěrů, silné univerzální banky",
    "option_d": "Rychlé financování rizikových inovací přes venture capital",
    "correct": "C",
    "explanation": "V kontinentálním modelu (Německo, ČR) jdou úspory hlavně přes banky do úvěrů. Ostatní možnosti popisují anglosaský tržní model.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 1
  },
  {
    "id": 5,
    "topic": "1BP404",
    "question": "Proč má ČR relativně malý a málo likvidní kapitálový trh? Vyberte nejlepší vysvětlení z pohledu modelu alokace úspor.",
    "option_a": "ČR patří k anglosaskému modelu s převahou burzovního financování",
    "option_b": "ČR patří k bankovnímu modelu, firmy se financují hlavně úvěry",
    "option_c": "ČR nemá žádnou burzu cenných papírů",
    "option_d": "Česká legislativa zakazuje firmám vydávat dluhopisy",
    "correct": "B",
    "explanation": "Česko je typický bankovní (kontinentální) model: firmy se financují hlavně úvěrem a úspory leží na vkladech, proto je kapitálový trh malý. BCPP přitom existuje od roku 1993.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 1
  },
  {
    "id": 6,
    "topic": "1BP404",
    "question": "Přiřaďte správně autora a přínos do investiční teorie:",
    "option_a": "Fama 1952: moderní teorie portfolia",
    "option_b": "Markowitz 1970: teorie efektivních trhů",
    "option_c": "Ross 1976: arbitrážní teorie oceňování",
    "option_d": "Sharpe 1934: fundamentální analýza",
    "correct": "C",
    "explanation": "Ross 1976 = APT. Markowitz 1952 = teorie portfolia, Sharpe 1964 = CAPM, Fama 1970 = efektivní trhy, Graham a Dodd 1934 = fundamentální analýza.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 1
  },
  {
    "id": 7,
    "topic": "1BP404",
    "question": "Disintermediace na finančních trzích znamená, že:",
    "option_a": "firmy si půjčují přímo na trhu (např. dluhopisy) místo přes banku",
    "option_b": "úvěry se přeměňují na obchodovatelné cenné papíry",
    "option_c": "úspory spravují převážně institucionální investoři",
    "option_d": "burzy se slučují do nadnárodních skupin",
    "correct": "A",
    "explanation": "Disintermediace = obcházení zprostředkovatele (banky), firma se financuje přímo na trhu. B je sekuritizace, C institucionalizace, D konsolidace.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 1
  },
  {
    "id": 8,
    "topic": "1BP404",
    "question": "Sekuritizace je:",
    "option_a": "přesun úspor z aktivních do pasivních fondů",
    "option_b": "zpřísnění regulace po finanční krizi",
    "option_c": "přeměna úvěrů (např. hypoték) na obchodovatelné cenné papíry",
    "option_d": "propojování národních trhů volným pohybem kapitálu",
    "correct": "C",
    "explanation": "Sekuritizace mění úvěry v cenné papíry (MBS, CDO). Její zneužití stálo u krize 2007–2009.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 1
  },
  {
    "id": 9,
    "topic": "1BP404",
    "question": "Vyberte NEPRAVDIVÉ tvrzení o funkcích sekundárního trhu:",
    "option_a": "Dává cenným papírům likviditu",
    "option_b": "Emitent z každého obchodu na sekundárním trhu dostává část výnosu",
    "option_c": "Tvoří cenu, která shrnuje informace trhu",
    "option_d": "Bez něj by byl primární trh méně atraktivní pro investory",
    "correct": "B",
    "explanation": "Na sekundárním trhu obchodují investoři mezi sebou, emitent z obchodu nic nedostává. Sekundární trh ale umožňuje primární trh, protože dává likviditu a cenu.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 1
  },
  {
    "id": 10,
    "topic": "1BP404",
    "question": "Který dlouhodobý trend na světových trzích popisuje přesun peněz z aktivně řízených fondů do indexových fondů a ETF?",
    "option_a": "Globalizace",
    "option_b": "Institucionalizace",
    "option_c": "Sekuritizace",
    "option_d": "Růst pasivního investování",
    "correct": "D",
    "explanation": "Pasivní investování: v USA pasivní fondy spravují víc peněz než aktivní (od přelomu 2023/2024). Institucionalizace znamená jen to, že úspory spravují instituce.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 1
  },
  {
    "id": 11,
    "topic": "1BP404",
    "question": "Který důvod NENÍ ekonomickým důvodem regulace kapitálového trhu?",
    "option_a": "Informační asymetrie mezi emitentem a investorem",
    "option_b": "Systémové riziko a nákaza mezi institucemi",
    "option_c": "Zajištění stabilního zisku finančních institucí",
    "option_d": "Ochrana drobných investorů a důvěra v trh",
    "correct": "C",
    "explanation": "Regulace řeší selhání trhu: informační asymetrii, systémové riziko, ochranu investorů a důvěru. Garantovat zisky institucí není jejím cílem.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 2
  },
  {
    "id": 12,
    "topic": "1BP404",
    "question": "Jaký model dohledu nad finančním trhem má ČR od 1. 4. 2006?",
    "option_a": "Sektorový model s Komisí pro cenné papíry",
    "option_b": "Integrovaný model, dohled vykonává ČNB",
    "option_c": "Twin peaks, ČNB a Ministerstvo financí",
    "option_d": "Funkcionální model s dohledem podle druhu činnosti",
    "correct": "B",
    "explanation": "Od 1. 4. 2006 přešla Komise pro cenné papíry i dozor nad pojišťovnami a penzijními fondy do ČNB, která je jediným (integrovaným) dohledem.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 2
  },
  {
    "id": 13,
    "topic": "1BP404",
    "question": "Model twin peaks znamená, že:",
    "option_a": "jeden orgán dohlíží na obezřetnost institucí a druhý na jejich jednání na trhu",
    "option_b": "dva orgány dohlížejí zvlášť na banky a pojišťovny",
    "option_c": "dohled vykonávají společně centrální banka a ministerstvo financí",
    "option_d": "každý stát EU má jeden národní a jeden evropský dohled",
    "correct": "A",
    "explanation": "Twin peaks dělí dohled podle cílů: obezřetnost (stabilita) a jednání s klienty (conduct). Příklad Nizozemsko, Austrálie, UK od 2013 (PRA + FCA).",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 2
  },
  {
    "id": 14,
    "topic": "1BP404",
    "question": "Velká Británie v roce 2013:",
    "option_a": "zavedla poprvé integrovaný dohled FSA",
    "option_b": "přešla ze sektorového na integrovaný model",
    "option_c": "zrušila FSA a přešla na model twin peaks (PRA + FCA)",
    "option_d": "přenesla dohled nad bankami na ECB",
    "correct": "C",
    "explanation": "FSA (integrovaný dohled od 1997) selhala v krizi (Northern Rock), proto UK v roce 2013 přešla na twin peaks. ECB nad britskými bankami nikdy nedohlížela.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 2
  },
  {
    "id": 15,
    "topic": "1BP404",
    "question": "Evropský systém finančního dohledu (ESFS) zahrnuje v makroobezřetnostní části:",
    "option_a": "ESMA",
    "option_b": "ESRB",
    "option_c": "EBA",
    "option_d": "EIOPA",
    "correct": "B",
    "explanation": "Makroobezřetnostní část ESFS tvoří ESRB (Evropská rada pro systémová rizika). EBA, EIOPA a ESMA tvoří mikroobezřetnostní část.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 2
  },
  {
    "id": 16,
    "topic": "1BP404",
    "question": "Vyberte NEPRAVDIVÉ tvrzení o ESFS:",
    "option_a": "Funguje od 1. 1. 2011",
    "option_b": "ESMA dohlíží přímo mimo jiné na ratingové agentury",
    "option_c": "ESRB vydává varování a doporučení bez závazných pravomocí",
    "option_d": "ECB v rámci ESFS přímo dohlíží na všechny české banky",
    "correct": "D",
    "explanation": "ČR není v eurozóně ani v bankovní unii, proto ECB (SSM) české banky přímo nedohlíží. Dohled nad nimi vykonává ČNB.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 2
  },
  {
    "id": 17,
    "topic": "1BP404",
    "question": "Makléř nakoupí akcie na vlastní účet těsně předtím, než provede velký nákupní pokyn klienta. Jde o:",
    "option_a": "front running",
    "option_b": "churning",
    "option_c": "Ponziho schéma",
    "option_d": "tunelování",
    "correct": "A",
    "explanation": "Front running = obchod na vlastní účet před známým pokynem klienta. Churning = zbytečně časté obchody na účtu klienta kvůli poplatkům.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 2
  },
  {
    "id": 18,
    "topic": "1BP404",
    "question": "Které nařízení EU zakazuje obchodování s vnitřní informací a manipulaci s trhem?",
    "option_a": "MiFIR",
    "option_b": "EMIR",
    "option_c": "MAR (Market Abuse Regulation)",
    "option_d": "SFDR",
    "correct": "C",
    "explanation": "MAR (596/2014, účinné od 2016) upravuje zneužívání trhu. EMIR upravuje OTC deriváty, SFDR udržitelnost, MiFIR transparentnost obchodování.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 2
  },
  {
    "id": 19,
    "topic": "1BP404",
    "question": "Které opatření patří k post-lehmanovskému přístupu k regulaci?",
    "option_a": "Zrušení Glass–Steagallova zákona",
    "option_b": "Bail-in: ztráty banky nesou akcionáři a věřitelé, ne daňoví poplatníci",
    "option_c": "Zrušení pojištění vkladů",
    "option_d": "Nahrazení státní regulace samoregulací burz",
    "correct": "B",
    "explanation": "Po roce 2008 přišly makroobezřetnost, Basel III, bail-in (BRRD), EMIR a ESFS. Glass–Steagall byl zrušen už v roce 1999.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 2
  },
  {
    "id": 20,
    "topic": "1BP404",
    "question": "Subjekty veřejného zájmu (např. kótovaní emitenti, banky, pojišťovny) mají v EU:",
    "option_a": "povinný výbor pro audit a rotaci auditora",
    "option_b": "výjimku z povinného auditu",
    "option_c": "povinnost být kótované na burze",
    "option_d": "zákaz vyplácet dividendy",
    "correct": "A",
    "explanation": "Pro subjekty veřejného zájmu platí přísnější pravidla auditu: výbor pro audit, rotace auditora, omezení neauditorských služeb. Je to reakce na skandály typu Enron.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 2
  },
  {
    "id": 21,
    "topic": "1BP404",
    "question": "Hlavní zákon upravující v ČR investiční služby, veřejné nabídky, regulovaný trh a zneužívání trhu je:",
    "option_a": "zákon o dohledu v oblasti kapitálového trhu (15/1998 Sb.)",
    "option_b": "zákon o investičních společnostech a fondech (240/2013 Sb.)",
    "option_c": "zákon o dluhopisech (190/2004 Sb.)",
    "option_d": "zákon o podnikání na kapitálovém trhu (256/2004 Sb.)",
    "correct": "D",
    "explanation": "Zákon o podnikání na kapitálovém trhu (256/2004 Sb.) převádí mimo jiné MiFID II. Zákon 15/1998 Sb. upravuje pravomoci dohledu.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 2
  },
  {
    "id": 22,
    "topic": "1BP404",
    "question": "Uzavřený fond má aktiva 520 mil. Kč, závazky 20 mil. Kč a 10 mil. akcií. Akcie se na burze obchoduje za 42 Kč. Jaký je diskont k NAV?",
    "option_a": "−19,2 %",
    "option_b": "−19,0 %",
    "option_c": "−16,0 %",
    "option_d": "−8,0 %",
    "correct": "C",
    "explanation": "NAV = (520 − 20) / 10 = 50 Kč, diskont = (42 − 50) / 50 = −16 %. Chyba −19,2 % vzniká zapomenutím závazků (52 Kč), −19 % dělením cenou 42 místo NAV.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 3
  },
  {
    "id": 23,
    "topic": "1BP404",
    "question": "Podílový fond podle českého práva:",
    "option_a": "je akciová společnost s proměnným základním kapitálem",
    "option_b": "nemá právní subjektivitu a spravuje ho investiční společnost",
    "option_c": "vydává investiční akcie s hlasovacím právem",
    "option_d": "je vždy uzavřeným fondem kótovaným na burze",
    "correct": "B",
    "explanation": "Podílový fond je jen oddělené jmění bez právní subjektivity, investor drží podílový list. A.s. s proměnným kapitálem je SICAV, tedy investiční fond.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 3
  },
  {
    "id": 24,
    "topic": "1BP404",
    "question": "Čím se liší otevřený fond od uzavřeného?",
    "option_a": "Otevřený fond průběžně vydává a odkupuje podíly za NAV",
    "option_b": "Otevřený fond se obchoduje jen na burze s diskontem k NAV",
    "option_c": "Uzavřený fond musí držet likvidní rezervu na odkupy",
    "option_d": "Uzavřený fond odkupuje podíly na žádost investora",
    "correct": "A",
    "explanation": "Otevřený fond vydává a odkupuje podíly (za NAV ± poplatky). Uzavřený má pevný počet akcií, neodkupuje je a investor je prodává na burze, často s diskontem.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 3
  },
  {
    "id": 25,
    "topic": "1BP404",
    "question": "Co udržuje tržní cenu ETF blízko jeho NAV?",
    "option_a": "Zákonný zákaz obchodovat ETF mimo NAV",
    "option_b": "Pevný počet podílů vydaných jednou",
    "option_c": "Vytváření a rušení podílů oprávněnými účastníky (arbitráž)",
    "option_d": "Povinnost správce denně odkupovat podíly od drobných investorů",
    "correct": "C",
    "explanation": "Oprávnění účastníci (authorized participants) vytvářejí nebo ruší podíly výměnou za koš akcií, kdykoli se cena odchýlí od NAV. Tato arbitráž drží cenu u NAV.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 3
  },
  {
    "id": 26,
    "topic": "1BP404",
    "question": "Pro hedge fondy je typické:",
    "option_a": "přísné limity UCITS a zákaz krátkých prodejů",
    "option_b": "investice jen do nekótovaných firem se strukturou GP/LP",
    "option_c": "pasivní kopírování indexu s nízkým TER",
    "option_d": "pákový efekt, krátké prodeje, cíl absolutního výnosu a poplatky 2/20",
    "correct": "D",
    "explanation": "Hedge fondy smějí používat páku, krátké prodeje a deriváty, cílí na absolutní výnos a účtují typicky 2 % + 20 % ze zisku. B popisuje private equity.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 3
  },
  {
    "id": 27,
    "topic": "1BP404",
    "question": "High-water mark u hedge fondu znamená, že:",
    "option_a": "výkonnostní poplatek se platí jen z výnosu nad předchozím maximem hodnoty podílu",
    "option_b": "fond smí mít maximálně dvojnásobnou páku",
    "option_c": "poplatek za správu se počítá z nejvyšší hodnoty majetku v roce",
    "option_d": "investor může odkoupit podíl jen při historickém maximu",
    "correct": "A",
    "explanation": "Po ztrátě musí fond nejdřív dohnat předchozí maximum, teprve pak si znovu bere podíl ze zisku.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 3
  },
  {
    "id": 28,
    "topic": "1BP404",
    "question": "Standardní fond podle ZISIF je:",
    "option_a": "fond kvalifikovaných investorů",
    "option_b": "speciální fond pro veřejnost mimo UCITS",
    "option_c": "fond splňující požadavky směrnice UCITS",
    "option_d": "uzavřený investiční fond kótovaný na BCPP",
    "correct": "C",
    "explanation": "Standardní fond = UCITS (evropský pas, přísná diverzifikace). Speciální fond je AIF pro veřejnost, FKI jsou jen pro kvalifikované investory.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 3
  },
  {
    "id": 29,
    "topic": "1BP404",
    "question": "Minimální investice do fondu kvalifikovaných investorů (FKI) v ČR je zpravidla:",
    "option_a": "100 000 Kč",
    "option_b": "1 mil. Kč (s testem vhodnosti)",
    "option_c": "10 mil. Kč",
    "option_d": "žádná, FKI je dostupný všem",
    "correct": "B",
    "explanation": "FKI jsou pro profesionální a bohaté investory, typicky od 1 mil. Kč s potvrzením vhodnosti. Mají mírnější pravidla a patří sem české hedge a PE fondy.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 3
  },
  {
    "id": 30,
    "topic": "1BP404",
    "question": "Který ukazatel shrnuje všechny průběžné roční náklady fondu v % z průměrného majetku?",
    "option_a": "NAV",
    "option_b": "Tracking error",
    "option_c": "Vstupní poplatek",
    "option_d": "TER (celková nákladovost)",
    "correct": "D",
    "explanation": "TER (total expense ratio) najdete ve sdělení klíčových informací (KID). Vstupní poplatek je jednorázový a do TER nepatří.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 3
  },
  {
    "id": 31,
    "topic": "1BP404",
    "question": "Vyberte NEPRAVDIVÉ vysvětlení, proč se uzavřené fondy obchodují s diskontem k NAV:",
    "option_a": "Poplatky za správu platí investor po celou dobu",
    "option_b": "Nedůvěra ve správce (např. tunelování)",
    "option_c": "Uzavřený fond musí podíly odkupovat za NAV, a proto je cena nižší",
    "option_d": "Nelikvidní nebo nadhodnocená aktiva v portfoliu",
    "correct": "C",
    "explanation": "Uzavřený fond podíly neodkupuje. Kdyby je odkupoval za NAV, diskont by nemohl přetrvat. Ostatní možnosti jsou uznávaná vysvětlení „hádanky uzavřených fondů“.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 3
  },
  {
    "id": 32,
    "topic": "1BP404",
    "question": "Private equity fond s fází „J-křivky“ znamená, že:",
    "option_a": "výnosy jsou v prvních letech záporné a zisky přicházejí až při prodeji firem",
    "option_b": "výnos kopíruje index s mírnou odchylkou",
    "option_c": "fond nejdřív vydělá a pak ztrácí",
    "option_d": "poplatky jsou nejvyšší na konci života fondu",
    "correct": "A",
    "explanation": "Na začátku převažují poplatky a investice, zisky se realizují až při exitu (IPO nebo prodeji) po 4–7 letech.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 3
  },
  {
    "id": 33,
    "topic": "1BP404",
    "question": "Dluhopis s nominálem 1 000 Kč, ročním kupónem 5 % a splatností 3 roky. Tržní požadovaný výnos je 4 %. Jaká je jeho cena?",
    "option_a": "972,77 Kč",
    "option_b": "1 000,00 Kč",
    "option_c": "1 138,75 Kč",
    "option_d": "1 027,75 Kč",
    "correct": "D",
    "explanation": "P = 50/1,04 + 50/1,04² + 1050/1,04³ = 48,08 + 46,23 + 933,45 = 1 027,75 Kč. Kupón je vyšší než výnos, proto je cena nad nominálem.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 4
  },
  {
    "id": 34,
    "topic": "1BP404",
    "question": "Co se stane s cenou již vydaného dluhopisu s pevným kupónem, když tržní úrokové sazby vzrostou?",
    "option_a": "Cena vzroste, protože dluhopis nese vyšší výnos",
    "option_b": "Cena klesne",
    "option_c": "Cena se nezmění, kupón je pevný",
    "option_d": "Cena klesne jen u dluhopisů s pohyblivým kupónem",
    "correct": "B",
    "explanation": "Cena = současná hodnota plateb. Vyšší diskontní sazba ji snižuje, cena a výnos se pohybují opačně. U FRN je citlivost naopak malá.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 4
  },
  {
    "id": 35,
    "topic": "1BP404",
    "question": "Dluhopis má kupón 6 % a výnos do splatnosti 7 %. Dluhopis se obchoduje:",
    "option_a": "pod nominální hodnotou",
    "option_b": "nad nominální hodnotou",
    "option_c": "přesně za nominální hodnotu",
    "option_d": "podle toho, kolik let zbývá do splatnosti, nad nebo pod nominálem",
    "correct": "A",
    "explanation": "Kupón < YTM → dluhopis s diskontem (pod nominálem). Investor dostane chybějící výnos z růstu ceny k nominálu do splatnosti.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 4
  },
  {
    "id": 36,
    "topic": "1BP404",
    "question": "Pomocí aproximace odhadněte YTM: nominál 1 000 Kč, kupón 80 Kč ročně, cena 960 Kč, splatnost 5 let.",
    "option_a": "8,00 %",
    "option_b": "8,33 %",
    "option_c": "9,00 %",
    "option_d": "7,35 %",
    "correct": "C",
    "explanation": "YTM ≈ (80 + (1000 − 960)/5) / ((1000 + 960)/2) = 88 / 980 = 8,98 % ≈ 9 %. 8,33 % je běžný výnos 80/960, který ignoruje růst ceny k nominálu.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 4
  },
  {
    "id": 37,
    "topic": "1BP404",
    "question": "Modifikovaná durace dluhopisu je 6. Výnosy vzrostou o 0,5 procentního bodu. Cena se přibližně změní o:",
    "option_a": "+3 %",
    "option_b": "−0,5 %",
    "option_c": "−6 %",
    "option_d": "−3 %",
    "correct": "D",
    "explanation": "ΔP/P ≈ −D_mod · Δr = −6 · 0,5 % = −3 %. Cena klesá, protože výnosy rostou.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 4
  },
  {
    "id": 38,
    "topic": "1BP404",
    "question": "Který dluhopis bude při stejné změně sazeb nejcitlivější na změnu ceny?",
    "option_a": "Desetiletý bezkupónový dluhopis",
    "option_b": "Desetiletý dluhopis s kupónem 8 %",
    "option_c": "Dvouletý dluhopis s kupónem 2 %",
    "option_d": "Dluhopis s pohyblivým kupónem (FRN)",
    "correct": "A",
    "explanation": "Durace roste se splatností a klesá s výší kupónu. Bezkupónový dluhopis má duraci rovnou splatnosti, tedy nejvyšší.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 4
  },
  {
    "id": 39,
    "topic": "1BP404",
    "question": "Konvertibilní dluhopis s nominálem 1 000 Kč lze vyměnit za 20 akcií. Akcie stojí 45 Kč, dluhopis 980 Kč. Jaká je konverzní prémie?",
    "option_a": "2,0 %",
    "option_b": "8,9 %",
    "option_c": "8,2 %",
    "option_d": "11,1 %",
    "correct": "B",
    "explanation": "Konverzní hodnota = 20 · 45 = 900 Kč, prémie = (980 − 900)/900 = 8,9 %. 8,2 % je chybné dělení cenou dluhopisu, 11,1 % srovnává nominál místo ceny.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 4
  },
  {
    "id": 40,
    "topic": "1BP404",
    "question": "Vyberte NEPRAVDIVÉ tvrzení o konvertibilních a opčních dluhopisech:",
    "option_a": "Konvertibilní dluhopis se mění za akcie a dluh zaniká",
    "option_b": "Warrant u opčního dluhopisu lze oddělit a prodat samostatně",
    "option_c": "Oba typy mají obvykle nižší kupón než běžný dluhopis téhož emitenta",
    "option_d": "Při uplatnění warrantu investor vymění dluhopis za akcie a emitent nedostane nové peníze",
    "correct": "D",
    "explanation": "U opčního dluhopisu investor akcie dokupuje za peníze a dluhopis trvá dál, emitent tedy nové peníze dostane. Výměnu dluhopisu popisuje konvertibilní dluhopis.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 4
  },
  {
    "id": 41,
    "topic": "1BP404",
    "question": "Nejnižší rating investičního stupně u agentury S&P je:",
    "option_a": "BBB−",
    "option_b": "BB+",
    "option_c": "A−",
    "option_d": "Baa3",
    "correct": "A",
    "explanation": "Investiční stupeň končí BBB− (S&P, Fitch), resp. Baa3 (Moody’s, ale to není škála S&P). BB+ je už spekulativní stupeň (junk).",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 4
  },
  {
    "id": 42,
    "topic": "1BP404",
    "question": "Proč prudce klesne cena dluhopisu, kterému rating spadne z BBB− na BB+?",
    "option_a": "Emitent musí okamžitě splatit celý dluh",
    "option_b": "Kupón se automaticky sníží",
    "option_c": "Mnoho institucí smí držet jen investiční stupeň, a vznikají nucené prodeje",
    "option_d": "Dluhopis se musí vyřadit z burzy",
    "correct": "C",
    "explanation": "Penzijní fondy, pojišťovny a mnoho fondů smí ze zákona nebo statutu držet jen investiční stupeň. Po pádu na junk musí prodávat (fallen angel).",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 4
  },
  {
    "id": 43,
    "topic": "1BP404",
    "question": "Který problém ratingových agentur se nejčastěji uvádí jako střet zájmů?",
    "option_a": "Agentury jsou vlastněny centrálními bankami",
    "option_b": "Model „platí emitent“: agenturu platí ten, koho hodnotí",
    "option_c": "Agentury hodnotí jen státní dluhopisy",
    "option_d": "Ratingy se mění denně podle ceny dluhopisu",
    "correct": "B",
    "explanation": "Issuer pays model vede k tlaku na příznivé ratingy (CDO s AAA před krizí 2007). Proto po krizi přišla regulace agentur a dohled ESMA.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 4
  },
  {
    "id": 44,
    "topic": "1BP404",
    "question": "Kupující dluhopisu mezi výplatními dny kupónu zaplatí:",
    "option_a": "čistou cenu bez naběhlého úroku",
    "option_b": "nominální hodnotu",
    "option_c": "čistou cenu sníženou o alikvotní úrokový výnos",
    "option_d": "hrubou cenu = čistá cena + alikvotní úrokový výnos",
    "correct": "D",
    "explanation": "Kótuje se čistá cena, ale platí se hrubá (špinavá) cena včetně AÚV. Prodávající tak dostane úrok za dobu, kdy dluhopis držel.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 4
  },
  {
    "id": 45,
    "topic": "1BP404",
    "question": "U penzijního plánu s definovaným příspěvkem (DC) nese investiční riziko:",
    "option_a": "zaměstnavatel, který musí dorovnat schodek",
    "option_b": "stát prostřednictvím I. pilíře",
    "option_c": "účastník, protože výše důchodu závisí na výnosech",
    "option_d": "penzijní společnost ze svého vlastního kapitálu",
    "correct": "C",
    "explanation": "DC = pevné jsou jen příspěvky, důchod závisí na výnosech, riziko nese účastník (např. české DPS, americký 401(k)). U DB nese riziko zaměstnavatel/fond.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 5
  },
  {
    "id": 46,
    "topic": "1BP404",
    "question": "Který český fond má zákonnou garanci nezáporného zhodnocení?",
    "option_a": "Transformovaný fond (bývalé penzijní připojištění)",
    "option_b": "Povinný konzervativní účastnický fond",
    "option_c": "Dynamický účastnický fond",
    "option_d": "Důchodový fond II. pilíře",
    "correct": "A",
    "explanation": "Garanci má jen transformovaný fond. Účastnické fondy DPS (včetně povinného konzervativního) garanci nemají. II. pilíř s důchodovými fondy byl zrušen.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 5
  },
  {
    "id": 47,
    "topic": "1BP404",
    "question": "II. pilíř (důchodové spoření) v ČR:",
    "option_a": "funguje od roku 1994 jako penzijní připojištění",
    "option_b": "fungoval jen v letech 2013–2015 a byl zrušen",
    "option_c": "je povinný pro všechny zaměstnance od roku 2024",
    "option_d": "je totéž co doplňkové penzijní spoření",
    "correct": "B",
    "explanation": "Důchodové spoření (zákon 426/2011 Sb.) fungovalo 2013–2015 a v roce 2016 byly peníze vráceny. DPS patří do III. pilíře.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 5
  },
  {
    "id": 48,
    "topic": "1BP404",
    "question": "Jaký je od 7/2024 maximální měsíční státní příspěvek k doplňkovému penzijnímu spoření?",
    "option_a": "230 Kč při příspěvku 1 000 Kč",
    "option_b": "500 Kč při příspěvku 2 500 Kč",
    "option_c": "340 Kč při příspěvku 1 700 Kč",
    "option_d": "100 Kč při příspěvku 500 Kč",
    "correct": "C",
    "explanation": "Od 7/2024: 20 % z příspěvku od 500 Kč, maximum 340 Kč při 1 700 Kč. 230 Kč při 1 000 Kč platilo před reformou.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 5
  },
  {
    "id": 49,
    "topic": "1BP404",
    "question": "Akcie A: výnos 10 %, σ = 20 %; akcie B: výnos 6 %, σ = 10 %; korelace 0,2; váhy 50/50. Jaká je směrodatná odchylka portfolia?",
    "option_a": "15,0 %",
    "option_b": "12,0 %",
    "option_c": "8,0 %",
    "option_d": "14,5 %",
    "correct": "B",
    "explanation": "σ² = 0,25·0,04 + 0,25·0,01 + 2·0,25·0,2·0,2·0,1 = 0,0145, σ = 12,0 %. 15 % je vážený průměr (platil by jen při korelaci 1), 8 % je výnos portfolia.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 5
  },
  {
    "id": 50,
    "topic": "1BP404",
    "question": "Diverzifikací lze odstranit:",
    "option_a": "systematické (tržní) riziko",
    "option_b": "úrokové riziko celého trhu",
    "option_c": "riziko recese",
    "option_d": "jedinečné (nesystematické) riziko",
    "correct": "D",
    "explanation": "S rostoucím počtem aktiv mizí riziko konkrétních firem. Systematické riziko (recese, sazby) zůstává, proto se za něj platí prémie.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 5
  },
  {
    "id": 51,
    "topic": "1BP404",
    "question": "Rozdíl mezi CML a SML:",
    "option_a": "CML má na ose x σ a platí pro efektivní portfolia; SML má na ose x betu a platí pro všechna aktiva",
    "option_b": "CML má na ose x betu, SML směrodatnou odchylku",
    "option_c": "CML platí pro jednotlivé akcie, SML jen pro tržní portfolio",
    "option_d": "Obě jsou totožné, liší se jen názvem",
    "correct": "A",
    "explanation": "CML (přímka kapitálového trhu): σ, jen efektivní portfolia. SML (CAPM): beta, všechna aktiva i portfolia.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 5
  },
  {
    "id": 52,
    "topic": "1BP404",
    "question": "r_f = 3 %, r_M = 9 %. Fond B: výnos 10 %, σ = 10 %, β = 0,8. Jaká je Jensenova alfa fondu B?",
    "option_a": "+1,0 p. b.",
    "option_b": "+2,2 p. b.",
    "option_c": "+7,0 p. b.",
    "option_d": "−0,8 p. b.",
    "correct": "B",
    "explanation": "Požadovaný výnos podle CAPM = 3 + 0,8·(9 − 3) = 7,8 %; α = 10 − 7,8 = +2,2 p. b. 1 p. b. je chybné srovnání přímo s trhem (10 − 9), 7 p. b. je jen riziková prémie fondu.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 5
  },
  {
    "id": 53,
    "topic": "1BP404",
    "question": "r_f = 3 %. Fond A: výnos 12 %, σ = 15 %, β = 1,2. Fond B: výnos 10 %, σ = 10 %, β = 0,8. Který fond je lepší podle Sharpova indexu?",
    "option_a": "Fond A, protože má vyšší výnos",
    "option_b": "Oba jsou stejné",
    "option_c": "Nelze určit bez výnosu trhu",
    "option_d": "Fond B (0,70 oproti 0,60)",
    "correct": "D",
    "explanation": "Sharpe A = (12 − 3)/15 = 0,60; B = (10 − 3)/10 = 0,70. Vyšší výnos A je jen odměnou za vyšší riziko.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 5
  },
  {
    "id": 54,
    "topic": "1BP404",
    "question": "Portfolio je jen malou částí jinak dobře diverzifikovaného majetku investora. Který ukazatel je pro jeho hodnocení nejvhodnější?",
    "option_a": "Treynorův index",
    "option_b": "Sharpův index",
    "option_c": "Prostý výnos",
    "option_d": "Směrodatná odchylka",
    "correct": "A",
    "explanation": "U dobře diverzifikovaného investora záleží jen na systematickém riziku (betě), proto Treynor. Sharpe (celkové riziko) je vhodný, když portfolio tvoří celý majetek.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 5
  },
  {
    "id": 55,
    "topic": "1BP404",
    "question": "Aktivní manažer dosáhl výnosu 12 %, benchmark 9 %, tracking error je 5 %. Information ratio je:",
    "option_a": "1,67",
    "option_b": "0,6",
    "option_c": "2,4",
    "option_d": "0,3",
    "correct": "B",
    "explanation": "IR = (r_p − r_B)/TE = (12 − 9)/5 = 0,6. Vyšší IR znamená víc nadvýnosu na jednotku odchylky od benchmarku.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 5
  },
  {
    "id": 56,
    "topic": "1BP404",
    "question": "Vyberte NEPRAVDIVÉ tvrzení o alokaci aktiv:",
    "option_a": "Strategická alokace určuje dlouhodobé cílové váhy tříd aktiv",
    "option_b": "Taktická alokace jsou dočasné odchylky od strategických vah",
    "option_c": "O většině kolísání výnosů portfolia rozhoduje výběr jednotlivých titulů, ne strategická alokace",
    "option_d": "Rebalancování vrací portfolio k cílovým vahám",
    "correct": "C",
    "explanation": "Podle Brinsona, Hooda a Beebowera (1986) vysvětluje strategická alokace přes 90 % rozptylu výnosů. Výběr titulů má menší vliv.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 5
  },
  {
    "id": 57,
    "topic": "1BP404",
    "question": "Arbitrážní teorie oceňování (APT) na rozdíl od CAPM:",
    "option_a": "vysvětluje výnos více systematickými faktory a stojí na neexistenci arbitráže",
    "option_b": "předpokládá, že jediným faktorem je tržní portfolio",
    "option_c": "přesně určuje, které makroekonomické faktory použít",
    "option_d": "odměňuje i jedinečné riziko firmy",
    "correct": "A",
    "explanation": "APT (Ross 1976): E(r) = r_f + Σβ_iλ_i, více faktorů, založená na neexistenci arbitráže. Které faktory to jsou, neříká, to musí určit empirie.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 5
  },
  {
    "id": 58,
    "topic": "1BP404",
    "question": "Proč podle „aritmetiky aktivní správy“ (Sharpe) aktivní fondy v průměru po nákladech zaostávají za pasivními?",
    "option_a": "Aktivní manažeři jsou méně vzdělaní",
    "option_b": "Pasivní fondy mají přístup k vnitřním informacím",
    "option_c": "Aktivní fondy smí investovat jen do malých firem",
    "option_d": "Všichni aktivní dohromady drží trh, takže mají před náklady tržní výnos, po vyšších nákladech tedy méně",
    "correct": "D",
    "explanation": "Součet aktivních pozic je tržní portfolio. Před náklady je průměrný aktivní výnos tržní, po nákladech nižší než u levného indexového fondu.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 5
  },
  {
    "id": 59,
    "topic": "1BP404",
    "question": "r_f = 3 %, očekávaný výnos trhu 8 %, beta akcie 1,4. Jaký je požadovaný výnos podle CAPM?",
    "option_a": "11,2 %",
    "option_b": "7,0 %",
    "option_c": "10,0 %",
    "option_d": "14,2 %",
    "correct": "C",
    "explanation": "E(r) = 3 + 1,4·(8 − 3) = 10 %. 11,2 % vznikne vynásobením celého výnosu trhu betou (1,4 · 8), 7 % je chybné 1,4 · 5.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 6
  },
  {
    "id": 60,
    "topic": "1BP404",
    "question": "Podle CAPM je požadovaný výnos akcie 10 %, analytik očekává výnos 12 %. Co z toho plyne?",
    "option_a": "Akcie leží nad SML, je podhodnocená, doporučení koupit",
    "option_b": "Akcie leží pod SML, je nadhodnocená, doporučení prodat",
    "option_c": "Akcie je správně oceněná",
    "option_d": "Beta akcie musí být záporná",
    "correct": "A",
    "explanation": "Očekávaný výnos > požadovaný → akcie nabízí víc, než odpovídá riziku (alfa +2 p. b.), leží nad SML a je podhodnocená.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 6
  },
  {
    "id": 61,
    "topic": "1BP404",
    "question": "Amihud a Mendelson (1986) vysvětlují prémii za nelikviditu především:",
    "option_a": "citlivostí výnosu akcie na šoky likvidity celého trhu",
    "option_b": "úrovní nelikvidity akcie měřenou bid-ask spreadem",
    "option_c": "velikostí firmy (SMB)",
    "option_d": "poměrem účetní a tržní hodnoty",
    "correct": "B",
    "explanation": "Amihud–Mendelson: očekávaný výnos roste se spreadem (úrovní nelikvidity), efekt klientely. Citlivost na tržní likviditu je model Pástora a Stambaugha.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 6
  },
  {
    "id": 62,
    "topic": "1BP404",
    "question": "Podle Pástora a Stambaugha (2003) požadují investoři vyšší výnos u akcií, které:",
    "option_a": "mají široký bid-ask spread",
    "option_b": "vyplácejí vysoké dividendy",
    "option_c": "ztrácejí hodnotu právě tehdy, když vysychá likvidita celého trhu",
    "option_d": "mají nízkou tržní kapitalizaci",
    "correct": "C",
    "explanation": "Pástor–Stambaugh: riziko likvidity jako systematický faktor (likviditní beta). Úroveň spreadu (A) je přístup Amihuda a Mendelsona.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 6
  },
  {
    "id": 63,
    "topic": "1BP404",
    "question": "Efekt klientely v modelu Amihuda a Mendelsona znamená, že:",
    "option_a": "nelikvidní aktiva drží investoři s dlouhým horizontem, protože se jim náklad spreadu rozloží",
    "option_b": "každá firma přitahuje akcionáře podle dividendové politiky",
    "option_c": "drobní investoři preferují ETF",
    "option_d": "likvidní aktiva drží penzijní fondy",
    "correct": "A",
    "explanation": "Dlouhodobý investor obchoduje zřídka, a proto mu spread tolik nevadí a získá prémii za nelikviditu. Možnost B je efekt klientely z dividendové politiky (téma 7).",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 6
  },
  {
    "id": 64,
    "topic": "1BP404",
    "question": "Akcie za rok vzroste o 50 % a další rok klesne o 50 %. Jaký je průměrný roční (geometrický) výnos?",
    "option_a": "0 %",
    "option_b": "−25 %",
    "option_c": "+12,5 %",
    "option_d": "−13,4 %",
    "correct": "D",
    "explanation": "√(1,5 · 0,5) − 1 = √0,75 − 1 = −13,4 %. Aritmetický průměr 0 % zkresluje, celková ztráta za 2 roky je −25 %.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 6
  },
  {
    "id": 65,
    "topic": "1BP404",
    "question": "Na trhu je bid 99 Kč a ask 101 Kč. Jaký je implicitní náklad jednoho nákupu (polovina spreadu vůči střední ceně)?",
    "option_a": "1 %",
    "option_b": "2 %",
    "option_c": "0,5 %",
    "option_d": "1,98 %",
    "correct": "A",
    "explanation": "Střední cena 100 Kč, kupujete za 101 → náklad 1 Kč = 1 %. Celý spread (2 %) zaplatíte, až když nakoupíte i prodáte.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 6
  },
  {
    "id": 66,
    "topic": "1BP404",
    "question": "Tříčlenný model Fama–French (1993) vysvětluje výnos akcie:",
    "option_a": "trhem, momentem a ziskovostí",
    "option_b": "trhem, velikostí firmy (SMB) a poměrem účetní a tržní hodnoty (HML)",
    "option_c": "trhem, likviditou a inflací",
    "option_d": "jen betou vůči tržnímu portfoliu",
    "correct": "B",
    "explanation": "FF3 = trh + SMB (malé − velké) + HML (value − growth). Momentum přidal Carhart (1997), ziskovost a investice pětifaktorový model (2015).",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 6
  },
  {
    "id": 67,
    "topic": "1BP404",
    "question": "Faktor HML v modelu Fama–French měří rozdíl výnosů:",
    "option_a": "akcií s vysokým a nízkým poměrem účetní a tržní hodnoty (value − growth)",
    "option_b": "malých a velkých firem",
    "option_c": "akcií s vysokou a nízkou betou",
    "option_d": "akcií s vysokým a nízkým dividendovým výnosem",
    "correct": "A",
    "explanation": "HML = high minus low book-to-market, tedy hodnotové mínus růstové akcie. Malé mínus velké je SMB.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 6
  },
  {
    "id": 68,
    "topic": "1BP404",
    "question": "Vyberte NEPRAVDIVÉ tvrzení o CAPM:",
    "option_a": "Odměňuje jen systematické riziko měřené betou",
    "option_b": "Předpokládá neomezené půjčování i ukládání za bezrizikovou sazbu",
    "option_c": "Empiricky je SML plošší, než model předpovídá",
    "option_d": "Tržní portfolio lze přesně pozorovat, a proto je model snadno testovatelný",
    "correct": "D",
    "explanation": "Rollova kritika (1977): skutečné tržní portfolio (všechna aktiva) nelze pozorovat, a proto CAPM nelze pořádně otestovat.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 6
  },
  {
    "id": 69,
    "topic": "1BP404",
    "question": "Které rozšíření CAPM nahrazuje bezrizikové aktivum portfoliem s nulovou betou?",
    "option_a": "Mezinárodní CAPM",
    "option_b": "Intertemporální CAPM (Merton)",
    "option_c": "Zero-beta CAPM (Black)",
    "option_d": "CAPM s likviditou (Acharya a Pedersen)",
    "correct": "C",
    "explanation": "Black (1972) uvolnil předpoklad neomezeného půjčování za r_f a nahradil bezrizikové aktivum portfoliem s nulovou betou.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 6
  },
  {
    "id": 70,
    "topic": "1BP404",
    "question": "Fyzická osoba v ČR prodá akcie, které držela 4 roky (zisk 200 000 Kč, příjem z prodeje pod 40 mil. Kč). Jak se zisk zdaní (stav 2025)?",
    "option_a": "Srážkovou daní 15 %",
    "option_b": "Je osvobozen díky časovému testu 3 roky",
    "option_c": "Daní 23 %",
    "option_d": "Je osvobozen, jen pokud hrubý příjem z prodeje nepřesáhl 100 000 Kč",
    "correct": "B",
    "explanation": "Časový test pro cenné papíry v ČR je 3 roky (od 2025 s limitem osvobození 40 mil. Kč ročně). Limit 100 000 Kč je samostatný důvod osvobození pro krátce držené papíry.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 6
  },
  {
    "id": 71,
    "topic": "1BP404",
    "question": "Proč nelze bitcoin ocenit stejným způsobem jako akcii nebo dluhopis?",
    "option_a": "Nemá peněžní toky (dividendu ani kupón), které by šlo diskontovat",
    "option_b": "Obchoduje se jen na regulovaných burzách",
    "option_c": "Jeho cenu stanovuje ECB",
    "option_d": "Má pevně danou vnitřní hodnotu",
    "correct": "A",
    "explanation": "Hodnota instrumentu = současná hodnota budoucích příjmů (základní myšlenka 4). Kryptoměny žádné příjmy nepřinášejí, cena je čistě věcí poptávky a nálady.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 6
  },
  {
    "id": 72,
    "topic": "1BP404",
    "question": "Firma letos vyplatila dividendu 19,23 Kč, dividendy trvale rostou o 4 %, požadovaná výnosnost je 10 %. Jaká je vnitřní hodnota akcie podle Gordonova modelu?",
    "option_a": "320,50 Kč",
    "option_b": "192,30 Kč",
    "option_c": "333,33 Kč",
    "option_d": "200,00 Kč",
    "correct": "C",
    "explanation": "D₁ = 19,23 · 1,04 = 20 Kč; V = 20 / (0,10 − 0,04) = 333,33 Kč. 320,50 Kč vznikne použitím D₀ místo D₁ (nejčastější chyba).",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 7
  },
  {
    "id": 73,
    "topic": "1BP404",
    "question": "Vnitřní hodnota akcie je 333 Kč, tržní cena 280 Kč. Fundamentální analytik doporučí:",
    "option_a": "prodat, akcie je nadhodnocená",
    "option_b": "koupit, akcie je podhodnocená",
    "option_c": "držet, rozdíl je v mezích chyby",
    "option_d": "krátce prodat, cena se vrátí k nule",
    "correct": "B",
    "explanation": "Cena < vnitřní hodnota → podhodnocená → koupit. Předpoklad je, že se cena k vnitřní hodnotě časem vrátí.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 7
  },
  {
    "id": 74,
    "topic": "1BP404",
    "question": "Jaké je správné pořadí fundamentální analýzy přístupem shora dolů (top-down)?",
    "option_a": "analýza firmy → odvětvová → globální",
    "option_b": "odvětvová → globální → analýza firmy",
    "option_c": "technická → globální → analýza firmy",
    "option_d": "globální (makro) → odvětvová → analýza firmy",
    "correct": "D",
    "explanation": "Top-down: nejdřív ekonomika (HDP, sazby, inflace), pak odvětví (cyklická × defenzivní), nakonec konkrétní firma a vnitřní hodnota.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 7
  },
  {
    "id": 75,
    "topic": "1BP404",
    "question": "Teorie irelevance dividendové politiky (Modigliani a Miller) tvrdí, že:",
    "option_a": "na dokonalém trhu nemá výše dividendy vliv na hodnotu firmy",
    "option_b": "investoři vždy preferují vyšší dividendy jako jistější příjem",
    "option_c": "zvýšení dividendy je signál důvěry managementu",
    "option_d": "dividendy snižují agentní náklady",
    "correct": "A",
    "explanation": "MM: akcionář si „dividendu“ vyrobí prodejem části akcií, hodnotu tvoří investiční politika. B je teorie ptáka v hrsti, C signalizační, D agentní.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 7
  },
  {
    "id": 76,
    "topic": "1BP404",
    "question": "Firma nečekaně sníží dividendu. Podle signalizační teorie cena akcie:",
    "option_a": "vzroste, protože firma víc investuje",
    "option_b": "se nezmění",
    "option_c": "obvykle klesne, protože trh to čte jako signál horších budoucích zisků",
    "option_d": "vzroste díky daňové úspoře akcionářů",
    "correct": "C",
    "explanation": "Management ví víc než trh a dividendy vyhlazuje. Snížení je proto silný negativní signál o budoucích ziscích.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 7
  },
  {
    "id": 77,
    "topic": "1BP404",
    "question": "V dualistickém systému řízení akciové společnosti je kontrolním orgánem:",
    "option_a": "představenstvo",
    "option_b": "správní rada",
    "option_c": "valná hromada",
    "option_d": "dozorčí rada",
    "correct": "D",
    "explanation": "Dualistický systém: představenstvo řídí, dozorčí rada kontroluje. Monistický má jedinou správní radu. Valná hromada je nejvyšší orgán v obou.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 7
  },
  {
    "id": 78,
    "topic": "1BP404",
    "question": "Oprávněné P/E podle Gordonova modelu je:",
    "option_a": "výplatní poměr / (k − g)",
    "option_b": "(k − g) / výplatní poměr",
    "option_c": "D₁ / (k − g)",
    "option_d": "ROE / k",
    "correct": "A",
    "explanation": "Z V = D₁/(k − g) a D₁ = výplatní poměr · E₁ plyne P/E = výplatní poměr / (k − g). Vyšší růst g nebo nižší požadovaný výnos k zvyšují oprávněné P/E.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 7
  },
  {
    "id": 79,
    "topic": "1BP404",
    "question": "Value screening vybere akcii s P/E 5, jejíž zisky ale v upadajícím odvětví rychle klesají. Jde o riziko:",
    "option_a": "momentum",
    "option_b": "value trap (past levné akcie)",
    "option_c": "high-water mark",
    "option_d": "efektu klientely",
    "correct": "B",
    "explanation": "Nízké P/E může odrážet oprávněné očekávání poklesu zisků. Screening je jen první krok, nutná je analýza, proč je akcie levná.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 7
  },
  {
    "id": 80,
    "topic": "1BP404",
    "question": "Fundamentální analýza je v rozporu s:",
    "option_a": "jen se slabou formou efektivnosti trhu",
    "option_b": "se středně silnou formou efektivnosti trhu",
    "option_c": "s žádnou formou efektivnosti",
    "option_d": "jen se silnou formou efektivnosti",
    "correct": "B",
    "explanation": "Středně silná forma: ceny obsahují všechny veřejné informace (výkazy), takže fundamentální analýza nepřinese nadvýnos. Se slabou formou je v rozporu technická analýza.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 7
  },
  {
    "id": 81,
    "topic": "1BP404",
    "question": "Koncepty „bezpečnostní polštář“ (margin of safety) a alegorie „pana Trhu“ pocházejí od:",
    "option_a": "Petera Lynche",
    "option_b": "Johna Templetona",
    "option_c": "Benjamina Grahama",
    "option_d": "André Kostolanyho",
    "correct": "C",
    "explanation": "Graham (Inteligentní investor): kupuj výrazně pod vnitřní hodnotou a trh ber jako náladového partnera. Lynch = GARP a PEG, Templeton = globální kontrarián.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 7
  },
  {
    "id": 82,
    "topic": "1BP404",
    "question": "Vyberte NEPRAVDIVÉ tvrzení o Gordonově modelu:",
    "option_a": "Předpokládá trvalý růst dividend konstantním tempem g",
    "option_b": "Vyžaduje, aby požadovaná výnosnost k byla vyšší než g",
    "option_c": "Hodnota klesá, když roste požadovaná výnosnost",
    "option_d": "Je vhodný i pro firmy, které dividendy nevyplácejí",
    "correct": "D",
    "explanation": "Pro firmy bez dividend model nefunguje, používají se modely volných peněžních toků (FCFE, FCFF) nebo tržní násobky.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 7
  },
  {
    "id": 83,
    "topic": "1BP404",
    "question": "Podle Dowovy teorie je sekundární trend:",
    "option_a": "hlavní trend trvající roky",
    "option_b": "korekce proti primárnímu trendu trvající týdny až měsíce",
    "option_c": "denní šum bez významu",
    "option_d": "trend dopravního indexu",
    "correct": "B",
    "explanation": "Primární = příliv (roky), sekundární = vlny (korekce 1/3 až 2/3 pohybu), terciární = vlnky (denní šum).",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 8
  },
  {
    "id": 84,
    "topic": "1BP404",
    "question": "Podle Dowovy teorie je nový býčí trend potvrzen, když:",
    "option_a": "nové maximum udělá průmyslový i dopravní index",
    "option_b": "RSI klesne pod 30",
    "option_c": "objem při růstech klesá",
    "option_d": "cena prorazí rezistenci na nízkém objemu",
    "correct": "A",
    "explanation": "Indexy se musí vzájemně potvrdit (firmy vyrábějí víc, musí se víc převážet) a objem má trend potvrzovat, tedy růst při růstech.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 8
  },
  {
    "id": 85,
    "topic": "1BP404",
    "question": "Index relativní síly (RSI) má hodnotu 78. Technický analytik to interpretuje jako:",
    "option_a": "přeprodaný trh, možný růst",
    "option_b": "zlatý kříž",
    "option_c": "překoupený trh, možný pokles",
    "option_d": "potvrzení klesajícího trendu",
    "correct": "C",
    "explanation": "RSI nad 70 = překoupeno, pod 30 = přeprodáno. V silném trendu ale oscilátory dávají falešné signály.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 8
  },
  {
    "id": 86,
    "topic": "1BP404",
    "question": "Zlatý kříž nastane, když:",
    "option_a": "cena klesne pod 200denní průměr",
    "option_b": "RSI protne hodnotu 50",
    "option_c": "dlouhý klouzavý průměr protne krátký zdola",
    "option_d": "krátký klouzavý průměr (např. 50denní) protne dlouhý (200denní) zdola",
    "correct": "D",
    "explanation": "Zlatý kříž = krátký MA protne dlouhý zdola (signál nákupu). Protnutí shora je kříž smrti.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 8
  },
  {
    "id": 87,
    "topic": "1BP404",
    "question": "Vyberte NEPRAVDIVÉ tvrzení o limitech technické analýzy:",
    "option_a": "Je v rozporu se slabou formou efektivnosti trhu",
    "option_b": "Oscilátory fungují nejlépe v silném trendu",
    "option_c": "Signály klouzavých průměrů přicházejí se zpožděním",
    "option_d": "Hrozí přeučení pravidel na historických datech",
    "correct": "B",
    "explanation": "Oscilátory (RSI) fungují v trhu bez trendu. V silném trendu může trh zůstat překoupený měsíce a dávají falešné signály.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 8
  },
  {
    "id": 88,
    "topic": "1BP404",
    "question": "Koncept „soutěže krásy“ (beauty contest), podle kterého investor odhaduje, co si budou myslet ostatní, pochází od:",
    "option_a": "Johna Maynarda Keynese",
    "option_b": "André Kostolanyho",
    "option_c": "Richarda Thalera",
    "option_d": "Charlese Dowa",
    "correct": "A",
    "explanation": "Keynes (Obecná teorie, 1936): soutěž krásy a zvířecí duchové (animal spirits).",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 8
  },
  {
    "id": 89,
    "topic": "1BP404",
    "question": "Podle Kostolanyho je tendence na burze dána:",
    "option_a": "ziskem firem a úrokovými sazbami",
    "option_b": "penězi a psychologií",
    "option_c": "objemem a cenou",
    "option_d": "inflací a kurzem",
    "correct": "B",
    "explanation": "Kostolany: tendence = peníze (likvidita, sazby) + psychologie (nálada). Když chybí obojí, ceny klesají.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 8
  },
  {
    "id": 90,
    "topic": "1BP404",
    "question": "Investor prodá akcie, které vzrostly, a ponechá si ty, které jsou ve ztrátě, s nadějí, že „se to vrátí“. Jde o:",
    "option_a": "mentální účetnictví",
    "option_b": "efekt dispozice",
    "option_c": "ukotvení",
    "option_d": "home bias",
    "correct": "B",
    "explanation": "Efekt dispozice je přímý důsledek teorie vyhlídek: u zisků averze k riziku (rychle prodat), u ztrát vyhledávání rizika (držet).",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 8
  },
  {
    "id": 91,
    "topic": "1BP404",
    "question": "Podle teorie vyhlídek (Kahneman a Tversky) platí:",
    "option_a": "ztráta bolí zhruba 2× víc, než potěší stejně velký zisk",
    "option_b": "lidé hodnotí výsledky podle celkového bohatství",
    "option_c": "u ztrát jsou lidé rizikově averzní",
    "option_d": "malé pravděpodobnosti lidé podceňují",
    "correct": "A",
    "explanation": "Averze ke ztrátě ≈ 2×, hodnocení vůči referenčnímu bodu, u ztrát lidé riziko vyhledávají a malé pravděpodobnosti přeceňují.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 8
  },
  {
    "id": 92,
    "topic": "1BP404",
    "question": "Rozdělování peněz do „přihrádek“ a odlišné zacházení s nimi (např. riskování s „penězi z výhry“) popsal jako mentální účetnictví:",
    "option_a": "Robert Shiller",
    "option_b": "Eugene Fama",
    "option_c": "Richard Thaler",
    "option_d": "Hyman Minsky",
    "correct": "C",
    "explanation": "Thaler (Nobelova cena 2017): mentální účetnictví. Shiller: bubliny a nadměrná volatilita.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 8
  },
  {
    "id": 93,
    "topic": "1BP404",
    "question": "Která spekulativní bublina byla komoditní?",
    "option_a": "Dot-com bublina 2000",
    "option_b": "Japonské akcie koncem 80. let",
    "option_c": "Záporné výnosy dluhopisů 2020–2021",
    "option_d": "Tulipánová mánie 1636–1637",
    "correct": "D",
    "explanation": "Tulipány (a ropa 2008, stříbro 1980) jsou komoditní bubliny. Dot-com a Japonsko jsou akciové, záporné výnosy 2020–2021 dluhopisová.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 8
  },
  {
    "id": 94,
    "topic": "1BP404",
    "question": "Proč racionální arbitrážníci často nezastaví bublinu krátkým prodejem?",
    "option_a": "Krátké prodeje jsou všude zakázané",
    "option_b": "Bublina může růst ještě dlouho a krátký prodejce mezitím zkrachuje",
    "option_c": "Arbitrážníci nemají informace o ceně",
    "option_d": "Krátký prodej zvyšuje cenu aktiva",
    "correct": "B",
    "explanation": "Limity arbitráže: „trh může zůstat iracionální déle, než vy zůstanete solventní“ (Keynes). Proto se i profesionálové často vezou s davem.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 8
  },
  {
    "id": 95,
    "topic": "1BP404",
    "question": "Ve středně silné formě efektivnosti ceny obsahují:",
    "option_a": "jen informace z minulých cen a objemů",
    "option_b": "všechny informace včetně neveřejných",
    "option_c": "všechny veřejně dostupné informace (včetně minulých cen)",
    "option_d": "jen makroekonomické informace",
    "correct": "C",
    "explanation": "Slabá = minulé ceny; středně silná = navíc všechny veřejné informace; silná = i neveřejné (vnitřní).",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 9
  },
  {
    "id": 96,
    "topic": "1BP404",
    "question": "Studie událostí (event study), jak rychle cena zareaguje na oznámení zisku, testuje:",
    "option_a": "slabou formu efektivnosti",
    "option_b": "středně silnou formu efektivnosti",
    "option_c": "silnou formu efektivnosti",
    "option_d": "platnost CAPM",
    "correct": "B",
    "explanation": "Event studies testují reakci na veřejné informace, tedy středně silnou formu. Autokorelace a runs test testují slabou, výsledky insiderů silnou.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 9
  },
  {
    "id": 97,
    "topic": "1BP404",
    "question": "Která forma efektivnosti na vyspělých trzích prokazatelně NEPLATÍ?",
    "option_a": "Silná forma",
    "option_b": "Slabá forma",
    "option_c": "Středně silná forma",
    "option_d": "Žádná, platí všechny tři",
    "correct": "A",
    "explanation": "Insideři dosahují nadprůměrných výnosů, proto je obchodování s vnitřní informací zakázané. Vyspělé trhy jsou efektivní zhruba ve středně silné formě.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 9
  },
  {
    "id": 98,
    "topic": "1BP404",
    "question": "Pokud trh platí ve středně silné formě efektivnosti, pak:",
    "option_a": "platí i silná forma",
    "option_b": "neplatí slabá forma",
    "option_c": "platí automaticky i slabá forma",
    "option_d": "technická analýza přináší nadvýnos",
    "correct": "C",
    "explanation": "Formy jsou vnořené: silná ⊃ středně silná ⊃ slabá. Středně silná zahrnuje slabou, opačně to neplatí.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 9
  },
  {
    "id": 99,
    "topic": "1BP404",
    "question": "Vyberte NEPRAVDIVÉ tvrzení o efektivním trhu:",
    "option_a": "Ceny se mění náhodně podle příchodu nových informací",
    "option_b": "Nelze soustavně dosahovat nadvýnosu po zohlednění rizika a nákladů",
    "option_c": "Ceny rychle odrážejí dostupné informace",
    "option_d": "Ceny jsou vždy přesně správné a nikdo se nemýlí",
    "correct": "D",
    "explanation": "Efektivní trh neznamená, že ceny jsou vždy správné. Chyby jsou náhodné (nahoru i dolů) a nelze je předem systematicky využít.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 9
  },
  {
    "id": 100,
    "topic": "1BP404",
    "question": "Grossmanův–Stiglitzův paradox říká, že:",
    "option_a": "dokonale efektivní trh není možný, protože by se nikomu nevyplatilo platit za analýzu",
    "option_b": "ceny akcií kolísají víc než dividendy",
    "option_c": "malé firmy vydělávají víc než velké",
    "option_d": "test efektivnosti je vždy i testem modelu oceňování",
    "correct": "A",
    "explanation": "Kdyby nikdo neanalyzoval, trh by efektivní nebyl. Rovnováha je „téměř efektivní“ trh. B je Shillerova nadměrná volatilita, D problém společné hypotézy.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 9
  },
  {
    "id": 101,
    "topic": "1BP404",
    "question": "Hypotéza adaptivních trhů (Andrew Lo) vysvětluje:",
    "option_a": "proč jsou všechny trhy vždy dokonale efektivní",
    "option_b": "proč se efektivnost mění v čase podle vývoje a přizpůsobování investorů",
    "option_c": "proč je CAPM přesný",
    "option_d": "proč insideři nevydělávají",
    "correct": "B",
    "explanation": "Volatilita efektivnosti: strategie funguje, dokud ji neobjeví příliš mnoho lidí. Efektivnost se mění v čase i mezi trhy.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 9
  },
  {
    "id": 102,
    "topic": "1BP404",
    "question": "Akcie, které rostly posledních 3–12 měsíců, v průměru rostou dál. Jde o anomálii:",
    "option_a": "lednový efekt",
    "option_b": "efekt velikosti",
    "option_c": "momentum",
    "option_d": "obrat (reversal)",
    "correct": "C",
    "explanation": "Momentum (Jegadeesh a Titman 1993). Obrat (De Bondt a Thaler) platí v horizontu 3–5 let, kdy se vítězové a poražení obracejí.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 9
  },
  {
    "id": 103,
    "topic": "1BP404",
    "question": "Které tvrzení o primárních emisích (IPO) odpovídá empirii?",
    "option_a": "První den cena obvykle klesne, dlouhodobě IPO porážejí trh",
    "option_b": "IPO jsou vždy oceněny přesně na vnitřní hodnotu",
    "option_c": "IPO nevykazují žádné cenové anomálie",
    "option_d": "První den cena obvykle vzroste, ale dlouhodobě IPO zaostávají za trhem",
    "correct": "D",
    "explanation": "Podhodnocení IPO (první den růst v průměru o desítky procent) a dlouhodobá podvýkonnost patří mezi speciální investiční příležitosti.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 9
  },
  {
    "id": 104,
    "topic": "1BP404",
    "question": "Proč může nadvýnos malých firem (size effect) být v souladu s efektivním trhem?",
    "option_a": "Malé firmy mohou nést riziko, které CAPM neměří, a nadvýnos je odměnou za něj",
    "option_b": "Malé firmy nemusí zveřejňovat výsledky",
    "option_c": "Malé firmy nejsou obchodovatelné",
    "option_d": "Efekt velikosti existuje jen v silné formě",
    "correct": "A",
    "explanation": "Problém společné hypotézy: test efektivnosti je i testem modelu rizika. „Anomálie“ může být jen nezměřená riziková prémie (Fama–French).",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 9
  },
  {
    "id": 105,
    "topic": "1BP404",
    "question": "Na jakém trhu je podle základních myšlenek předmětu největší prostor pro dlouhodobě nadprůměrné výsledky díky fundamentální analýze?",
    "option_a": "Na vysoce likvidním trhu velkých amerických akcií",
    "option_b": "Na trhu státních dluhopisů USA",
    "option_c": "Na méně vyspělém a málo likvidním trhu",
    "option_d": "Na žádném, nadvýnos nelze dosáhnout nikde",
    "correct": "C",
    "explanation": "Základní myšlenka 6: na méně vyspělých, málo likvidních trzích lze nadprůměrných výsledků dosahovat i dlouhodobě. Vyspělé trhy jsou efektivní ve středně silné formě.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 9
  },
  {
    "id": 106,
    "topic": "1BP404",
    "question": "Spekulativní útok na fixní kurz, vyčerpání devizových rezerv a prudké znehodnocení měny jsou znaky:",
    "option_a": "bankovní krize",
    "option_b": "dluhové krize",
    "option_c": "akciového krachu",
    "option_d": "měnové krize",
    "correct": "D",
    "explanation": "Měnová krize: libra 1992, česká koruna 5/1997, asijská krize 1997. Dluhová krize = stát nemůže splácet (Řecko, Argentina).",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 10
  },
  {
    "id": 107,
    "topic": "1BP404",
    "question": "Podle Minskyho hypotézy finanční nestability dlužník, který nesplácí ani úrok a spoléhá jen na růst ceny aktiva, používá:",
    "option_a": "zajištěné (hedge) financování",
    "option_b": "Ponziho financování",
    "option_c": "spekulativní financování",
    "option_d": "mezaninové financování",
    "correct": "B",
    "explanation": "Minsky: zajištěné (splácí úrok i jistinu) → spekulativní (jen úrok, jistinu refinancuje) → Ponziho (ani úrok, spoléhá na růst cen). Stabilita plodí nestabilitu.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 10
  },
  {
    "id": 108,
    "topic": "1BP404",
    "question": "Banka Lehman Brothers padla:",
    "option_a": "19. 10. 1987",
    "option_b": "15. 9. 2008",
    "option_c": "24. 10. 1929",
    "option_d": "6. 5. 2010",
    "correct": "B",
    "explanation": "15. 9. 2008 = pád Lehmanu. 19. 10. 1987 = černé pondělí, 24. 10. 1929 = černý čtvrtek, 6. 5. 2010 = flash crash.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 10
  },
  {
    "id": 109,
    "topic": "1BP404",
    "question": "Co bylo spíše SPOUŠTĚČEM než hlubokou příčinou globální finanční krize 2007–2009?",
    "option_a": "Pád banky Lehman Brothers",
    "option_b": "Nemovitostní bublina v USA",
    "option_c": "Hypotéky subprime a jejich sekuritizace s ratingem AAA",
    "option_d": "Vysoká páka bank a slabá regulace stínového bankovnictví",
    "correct": "A",
    "explanation": "Pád Lehmanu krizi vyhrotil, ale příčinou bylo nahromaděné zadlužení, bublina, špatné hypotéky, sekuritizace a selhání regulace. V eseji tyto roviny odlišujte.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 10
  },
  {
    "id": 110,
    "topic": "1BP404",
    "question": "Hedge fond LTCM, zachráněný v roce 1998 konsorciem bank pod patronací Fedu, měl problém hlavně kvůli:",
    "option_a": "podvodu typu Ponziho schéma",
    "option_b": "investicím do dot-com akcií",
    "option_c": "vysoké páce a ztrátám po ruském moratoriu",
    "option_d": "úpadku ratingové agentury",
    "correct": "C",
    "explanation": "LTCM měl obrovskou páku (cca 25:1 v rozvaze) a ruské moratorium v roce 1998 vyvolalo ztráty. Záchrana měla zabránit systémové krizi.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 10
  },
  {
    "id": 111,
    "topic": "1BP404",
    "question": "Bail-in znamená, že ztráty banky v krizi nesou:",
    "option_a": "daňoví poplatníci prostřednictvím státní injekce",
    "option_b": "centrální banka tiskem peněz",
    "option_c": "vkladatelé s pojištěnými vklady do limitu",
    "option_d": "akcionáři a věřitelé banky",
    "correct": "D",
    "explanation": "Bail-in (BRRD v EU, 2014) = odpis nebo konverze nároků akcionářů a věřitelů. Bail-out = záchrana penězi daňových poplatníků.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 10
  },
  {
    "id": 112,
    "topic": "1BP404",
    "question": "Které opatření patří k Basel III?",
    "option_a": "Ukazatele likvidity LCR a NSFR a pákový poměr",
    "option_b": "Zákaz obchodování bank na vlastní účet",
    "option_c": "Oddělení retailového bankovnictví (ring-fencing)",
    "option_d": "Zřízení úřadu na ochranu spotřebitele CFPB",
    "correct": "A",
    "explanation": "Basel III: víc a kvalitnějšího kapitálu, kapitálové rezervy, pákový poměr, LCR a NSFR. B je Volcker, C Vickers, D Dodd-Frank.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 10
  },
  {
    "id": 113,
    "topic": "1BP404",
    "question": "Vyberte NEPRAVDIVÉ tvrzení o důsledcích finančních krizí:",
    "option_a": "Recese po bankovních krizích bývají hlubší a delší než běžné",
    "option_b": "Veřejný dluh po bankovní krizi obvykle výrazně roste",
    "option_c": "Po krizi obvykle přijde deregulace, protože se ukáže, že regulace brzdila trh",
    "option_d": "Banky omezují úvěry i zdravým firmám (credit crunch)",
    "correct": "C",
    "explanation": "Po velkých krizích naopak přichází nová regulace: 1929 → Glass–Steagall a SEC, Enron → Sarbanes-Oxley, 2008 → Dodd-Frank a Basel III.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 10
  },
  {
    "id": 114,
    "topic": "1BP404",
    "question": "Co uklidnilo dluhovou krizi eurozóny v roce 2012?",
    "option_a": "Vystoupení Řecka z eurozóny",
    "option_b": "Draghiho výrok „whatever it takes“ a program OMT",
    "option_c": "Zrušení Paktu stability a růstu",
    "option_d": "Zvýšení úrokových sazeb ECB na 5 %",
    "correct": "B",
    "explanation": "Závazek ECB udělat vše pro záchranu eura (7/2012) a program OMT snížily výnosy dluhopisů periferie. Řecko z eurozóny nevystoupilo.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 10
  },
  {
    "id": 115,
    "topic": "1BP404",
    "question": "Začarovaný kruh banky–stát (doom loop) v eurozóně znamená, že:",
    "option_a": "banky drží státní dluhopisy a stát zachraňuje banky, takže problém jednoho táhne druhého",
    "option_b": "centrální banka financuje stát přímo tiskem peněz",
    "option_c": "státy zakazují bankám držet státní dluhopisy",
    "option_d": "banky přestávají přijímat vklady",
    "correct": "A",
    "explanation": "Pokles cen státních dluhopisů oslabuje banky a záchrana bank zvyšuje dluh státu. Proto vznikla bankovní unie.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 10
  },
  {
    "id": 116,
    "topic": "1BP404",
    "question": "Který společný rys se objevuje téměř u všech finančních krizí?",
    "option_a": "Nízké zadlužení domácností",
    "option_b": "Pevné regulované ceny aktiv",
    "option_c": "Přílišné zadlužení (páka) a bublina na nějakém aktivu",
    "option_d": "Deflace v období boomu",
    "correct": "C",
    "explanation": "Společné rysy: páka, bublina, nesoulad splatností nebo měn, víra, že „tentokrát je to jinak“, a selhání regulace.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 10
  },
  {
    "id": 117,
    "topic": "1BP404",
    "question": "Český investor koupí americké akcie při kurzu 25 CZK/USD. Akcie za rok vzrostou o 10 % v USD, koruna posílí na 22 CZK/USD. Jaký je výnos v korunách?",
    "option_a": "−3,2 %",
    "option_b": "+10,0 %",
    "option_c": "−2,0 %",
    "option_d": "+22,0 %",
    "correct": "A",
    "explanation": "(1 + r_CZK) = 1,10 · (22/25) = 0,968 → −3,2 %. Posílení koruny snižuje výnos zahraniční investice. −2 % je chybný prostý součet (+10 − 12).",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 11
  },
  {
    "id": 118,
    "topic": "1BP404",
    "question": "Hlavním přínosem mezinárodního investování je:",
    "option_a": "odstranění měnového rizika",
    "option_b": "diverzifikace díky nedokonalé korelaci zahraničních a domácího trhu",
    "option_c": "nižší transakční náklady než doma",
    "option_d": "garantovaný vyšší výnos",
    "correct": "B",
    "explanation": "Hlavní výhoda je diverzifikace. Měnové riziko naopak přibývá a náklady bývají vyšší.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 11
  },
  {
    "id": 119,
    "topic": "1BP404",
    "question": "Vyberte NEPRAVDIVÉ tvrzení o mezinárodní diverzifikaci:",
    "option_a": "S globalizací korelace mezi trhy dlouhodobě roste",
    "option_b": "V krizích korelace prudce vzrostou",
    "option_c": "Přináší nové riziko: měnové a riziko země",
    "option_d": "Nejvíc chrání právě v krizích, protože trhy padají nezávisle",
    "correct": "D",
    "explanation": "V krizích (2008) padají trhy najednou, korelace rostou a diverzifikace selhává, právě když je nejvíc potřeba.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 11
  },
  {
    "id": 120,
    "topic": "1BP404",
    "question": "Certifikát vydaný americkou bankou na akcie zahraniční firmy, obchodovaný v USA v dolarech, je:",
    "option_a": "GDR",
    "option_b": "REIT",
    "option_c": "ADR",
    "option_d": "ETC",
    "correct": "C",
    "explanation": "ADR = American Depositary Receipt. GDR je obdoba obchodovaná na více trzích (často v Londýně).",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 11
  },
  {
    "id": 121,
    "topic": "1BP404",
    "question": "Investoři drží mnohem víc domácích akcií, než odpovídá podílu jejich země na světovém trhu. Tento jev se nazývá:",
    "option_a": "home bias (domácí zaujatost)",
    "option_b": "efekt dispozice",
    "option_c": "segmentace trhu",
    "option_d": "survivorship bias",
    "correct": "A",
    "explanation": "Hádanka domácí zaujatosti: důvody jsou znalost domácích firem, měnové riziko, náklady, daně, regulace a behaviorální faktory.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 11
  },
  {
    "id": 122,
    "topic": "1BP404",
    "question": "Co obvykle vede k RŮSTU ceny zlata?",
    "option_a": "Růst reálných úrokových sazeb",
    "option_b": "Posilování amerického dolaru",
    "option_c": "Klid na trzích a optimismus investorů",
    "option_d": "Pokles reálných úrokových sazeb",
    "correct": "D",
    "explanation": "Zlato nenese úrok, jeho nákladem příležitosti je reálná sazba. Pokles reálných sazeb, slabý dolar a krize jeho cenu zvyšují.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 11
  },
  {
    "id": 123,
    "topic": "1BP404",
    "question": "Investiční zlato v EU je z hlediska DPH:",
    "option_a": "zdaněno základní sazbou",
    "option_b": "osvobozeno od DPH",
    "option_c": "zdaněno sníženou sazbou",
    "option_d": "zdaněno jen při prodeji do zahraničí",
    "correct": "B",
    "explanation": "Investiční zlato (slitky, mince) je v EU osvobozeno od DPH, což ho odlišuje od stříbra a šperků.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 11
  },
  {
    "id": 124,
    "topic": "1BP404",
    "question": "Který motiv NEPATŘÍ mezi typické motivy investování do reálných aktiv?",
    "option_a": "Ochrana proti inflaci",
    "option_b": "Diverzifikace díky nízké korelaci s akciemi",
    "option_c": "Vysoká likvidita a nízké transakční náklady",
    "option_d": "Bezpečný přístav v krizích",
    "correct": "C",
    "explanation": "Reálná aktiva mají naopak nízkou likviditu a vysoké transakční náklady (poplatky, úschova, pojištění).",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 11
  },
  {
    "id": 125,
    "topic": "1BP404",
    "question": "Proč růst úrokových sazeb v letech 2022–2023 snížil ceny komerčních nemovitostí?",
    "option_a": "Hodnota ≈ čistý nájem / kapitalizační míra; ta s růstem sazeb roste",
    "option_b": "Nájemné se ze zákona snížilo",
    "option_c": "REIT musely přestat vyplácet dividendy",
    "option_d": "Nemovitosti se začaly zdaňovat DPH",
    "correct": "A",
    "explanation": "Vyšší požadovaná výnosnost (cap rate) znamená nižší hodnotu při stejném nájmu, stejně jako u dluhopisu.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 11
  },
  {
    "id": 126,
    "topic": "1BP404",
    "question": "Proč bývají výnosové indexy netradičních aktiv (umění, víno) nadsazené?",
    "option_a": "Jsou zdaněné vyšší sazbou",
    "option_b": "Zahrnují jen prodané kusy (survivorship bias) a nezapočítávají náklady na transakce a úschovu",
    "option_c": "Oceňují se denně na burze",
    "option_d": "Nejsou nadsazené, přesně odpovídají výnosu investora",
    "correct": "B",
    "explanation": "Neprodejné kusy z indexu zmizí a vysoké aukční poplatky a úschova se nezapočítávají. Nízká volatilita je často dána tím, že se aktivum neoceňuje denně.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 11
  },
  {
    "id": 127,
    "topic": "1BP404",
    "question": "Který vývoj charakterizuje mezinárodní investování po roce 2008?",
    "option_a": "Dominance rozvíjejících se trhů v globálních indexech",
    "option_b": "Pokles podílu USA v indexu MSCI World pod 30 %",
    "option_c": "Dominance amerického trhu a růst globálních pasivních ETF",
    "option_d": "Zákaz mezinárodních investic v EU",
    "correct": "C",
    "explanation": "Po roce 2008 dominuje americký trh (přes 60 % MSCI World, technologické firmy), rostou levná globální ETF a sílí geopolitická fragmentace.",
    "created_at": "2026-09-24 08:32:28",
    "subtopic": 11
  },
  {
    "id": 128,
    "topic": "1BP404",
    "question": "Volckerovo pravidlo (součást Dodd-Frank Act) bankám s pojištěnými vklady:",
    "option_a": "zakazuje obchodování na vlastní účet a omezuje vlastnictví hedge a PE fondů",
    "option_b": "nařizuje oddělit retailové bankovnictví do samostatné dceřiné společnosti",
    "option_c": "zakazuje upisování emisí akcií",
    "option_d": "nařizuje sloučit komerční a investiční bankovnictví",
    "correct": "A",
    "explanation": "Volcker = zákaz proprietary tradingu a omezení hedge a PE fondů (max. 3 %). Oddělení retailu (ring-fencing) je Vickersovo pravidlo.",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 12
  },
  {
    "id": 129,
    "topic": "1BP404",
    "question": "Vickersovo pravidlo ve Velké Británii:",
    "option_a": "zakazuje bankám jakékoli investiční bankovnictví",
    "option_b": "vyžaduje ohrazení (ring-fencing) retailového bankovnictví velkých bank do samostatného subjektu",
    "option_c": "zavádí pojištění vkladů",
    "option_d": "je součástí amerického Dodd-Frank Act",
    "correct": "B",
    "explanation": "Vickers (zpráva 2011, účinné od 1. 1. 2019): retailová část banky s vlastním kapitálem a vedením, investiční bankovnictví mimo ohrazení.",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 12
  },
  {
    "id": 130,
    "topic": "1BP404",
    "question": "Glass–Steagallův zákon z roku 1933, který v USA oddělil komerční a investiční bankovnictví, zrušil:",
    "option_a": "Dodd-Frank Act v roce 2010",
    "option_b": "Sarbanes-Oxley Act v roce 2002",
    "option_c": "Gramm–Leach–Bliley Act v roce 1999",
    "option_d": "Investment Company Act v roce 1940",
    "correct": "C",
    "explanation": "Gramm–Leach–Bliley Act (1999) legalizoval finanční supermarkety (Citigroup). Dodd-Frank Glass–Steagall neobnovil, jen zavedl Volckerovo pravidlo.",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 12
  },
  {
    "id": 131,
    "topic": "1BP404",
    "question": "Při upsání emise formou pevného závazku (firm commitment) nese riziko neprodání:",
    "option_a": "emitent",
    "option_b": "regulátor",
    "option_c": "investoři na sekundárním trhu",
    "option_d": "upisující banka (syndikát)",
    "correct": "D",
    "explanation": "Banka celou emisi koupí za pevnou cenu a prodává dál na své riziko. U best effort nese riziko emitent.",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 12
  },
  {
    "id": 132,
    "topic": "1BP404",
    "question": "Který model začlenění investičního bankovnictví je typický pro Německo a ČR?",
    "option_a": "Univerzální bankovnictví",
    "option_b": "Oddělené bankovnictví",
    "option_c": "Twin peaks",
    "option_d": "Offshore bankovnictví",
    "correct": "A",
    "explanation": "Kontinentální Evropa má univerzální banky (Deutsche Bank). Oddělené bankovnictví platilo v USA v letech 1933–1999.",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 12
  },
  {
    "id": 133,
    "topic": "1BP404",
    "question": "Vyberte NEPRAVDIVÉ tvrzení o Dodd-Frank Act:",
    "option_a": "Byl přijat v USA v roce 2010",
    "option_b": "Zřídil radu FSOC pro dohled nad systémovým rizikem",
    "option_c": "Zavedl ponechání části rizika (5 %) při sekuritizaci",
    "option_d": "Obnovil úplné oddělení komerčního a investičního bankovnictví podle Glass–Steagallova zákona",
    "correct": "D",
    "explanation": "Dodd-Frank Glass–Steagall neobnovil, zavedl jen užší Volckerovo pravidlo. V roce 2018 byl částečně zmírněn.",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 12
  },
  {
    "id": 134,
    "topic": "1BP404",
    "question": "MiFID II a nařízení MiFIR jsou účinné od:",
    "option_a": "1. 11. 2007",
    "option_b": "3. 1. 2018",
    "option_c": "1. 1. 2011",
    "option_d": "17. 1. 2025",
    "correct": "B",
    "explanation": "MiFID I platila od 11/2007, MiFID II a MiFIR od 3. 1. 2018. 1. 1. 2011 = start ESFS, 17. 1. 2025 = DORA.",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 12
  },
  {
    "id": 135,
    "topic": "1BP404",
    "question": "Obchodník poskytuje klientovi investiční poradenství. Jaký test musí podle MiFID II provést?",
    "option_a": "Test přiměřenosti",
    "option_b": "Žádný, u poradenství se testy nedělají",
    "option_c": "Test vhodnosti (znalosti, finanční situace, cíle, tolerance rizika)",
    "option_d": "Jen ověření totožnosti (KYC)",
    "correct": "C",
    "explanation": "Test vhodnosti = investiční poradenství a správa portfolia. Test přiměřenosti = ostatní služby (rozumí klient produktu?).",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 12
  },
  {
    "id": 136,
    "topic": "1BP404",
    "question": "Podle MiFID II mají nejmenší míru ochrany:",
    "option_a": "neprofesionální klienti",
    "option_b": "profesionální klienti na žádost",
    "option_c": "drobní investoři s portfoliem nad 1 mil. Kč",
    "option_d": "způsobilé protistrany (banky, pojišťovny)",
    "correct": "D",
    "explanation": "Kategorie: neprofesionální (nejvyšší ochrana) → profesionální → způsobilé protistrany (nejmenší ochrana).",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 12
  },
  {
    "id": 137,
    "topic": "1BP404",
    "question": "Informační bariéry mezi odděleními investiční banky (např. poradenství při M&A a obchodováním) se nazývají:",
    "option_a": "čínské zdi",
    "option_b": "ring-fencing",
    "option_c": "high-water mark",
    "option_d": "circuit breakers",
    "correct": "A",
    "explanation": "Čínské zdi řeší střet zájmů v investiční bance. Ring-fencing je Vickersovo oddělení retailu, circuit breakers jsou obchodní přestávky na burze.",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 12
  },
  {
    "id": 138,
    "topic": "1BP404",
    "question": "Alternativní obchodní platforma, kterou může podle MiFID provozovat i obchodník s cennými papíry a která má mírnější pravidla pro emitenty než burza, je:",
    "option_a": "regulovaný trh",
    "option_b": "MTF (mnohostranný obchodní systém)",
    "option_c": "systematický internalizátor",
    "option_d": "centrální depozitář",
    "correct": "B",
    "explanation": "MTF je alternativní systém (např. Cboe Europe, Start BCPP). Systematický internalizátor provádí pokyny proti vlastnímu účtu.",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 13
  },
  {
    "id": 139,
    "topic": "1BP404",
    "question": "OTF (organizovaný obchodní systém) zavedený MiFID II se používá:",
    "option_a": "pro akcie všech kótovaných firem",
    "option_b": "jen pro podílové listy fondů",
    "option_c": "pro dluhopisy, deriváty a emisní povolenky, ne pro akcie",
    "option_d": "výhradně pro kryptoaktiva",
    "correct": "C",
    "explanation": "OTF slouží jen pro nekapitálové instrumenty (dluhopisy, deriváty, povolenky), s akciemi se na něm neobchoduje.",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 13
  },
  {
    "id": 140,
    "topic": "1BP404",
    "question": "Trh, kde tvůrci trhu průběžně kotují nákupní a prodejní cenu a jsou povinni za ni obchodovat, je:",
    "option_a": "quote-driven (řízený kotacemi)",
    "option_b": "order-driven (řízený pokyny)",
    "option_c": "aukční trh",
    "option_d": "dark pool",
    "correct": "A",
    "explanation": "Quote-driven = market makers kotují bid/ask (tradičně Nasdaq, dluhopisy). Order-driven = párování pokynů v knize pokynů (BCPP, většina evropských burz).",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 13
  },
  {
    "id": 141,
    "topic": "1BP404",
    "question": "Vyberte NEPRAVDIVÉ tvrzení o vysokofrekvenčním obchodování (HFT):",
    "option_a": "Využívá co-location serverů v datovém centru burzy",
    "option_b": "Za normálních podmínek zužuje spready",
    "option_c": "Spojuje se s bleskovým propadem 6. 5. 2010",
    "option_d": "Poskytuje stabilní likviditu i v krizích, protože HFT firmy musí držet pozice přes noc",
    "correct": "D",
    "explanation": "Likvidita HFT je „fantomová“: v krizi HFT z trhu mizí. HFT pozice přes noc typicky nedrží.",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 13
  },
  {
    "id": 142,
    "topic": "1BP404",
    "question": "REIT je:",
    "option_a": "burzovně obchodovaná nemovitostní společnost, která musí vyplácet většinu zisku (v USA 90 %) jako dividendy",
    "option_b": "prázdná společnost, která na burze získá peníze a pak převezme soukromou firmu",
    "option_c": "fond kvalifikovaných investorů investující do půdy",
    "option_d": "státní nemovitostní fond",
    "correct": "A",
    "explanation": "REIT výměnou za vyplácení většiny zisku neplatí daň z příjmu na úrovni firmy. Popis B odpovídá SPAC.",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 13
  },
  {
    "id": 143,
    "topic": "1BP404",
    "question": "Prázdná společnost bez podnikání, která na burze získá peníze a má obvykle 2 roky na převzetí soukromé firmy, se nazývá:",
    "option_a": "REIT",
    "option_b": "ETF",
    "option_c": "SPAC",
    "option_d": "SICAV",
    "correct": "C",
    "explanation": "SPAC (special purpose acquisition company, „bianco šek“) zažil boom v letech 2020–2021, pak útlum a zpřísnění pravidel SEC.",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 13
  },
  {
    "id": 144,
    "topic": "1BP404",
    "question": "Burza cenných papírů Praha:",
    "option_a": "zahájila obchodování v roce 2006",
    "option_b": "je od roku 2008 součástí skupiny Vídeňské burzy (CEESEG)",
    "option_c": "patří skupině Deutsche Börse",
    "option_d": "je provozována ČNB",
    "correct": "B",
    "explanation": "BCPP obchoduje od dubna 1993 a od roku 2008 patří do skupiny Vídeňské burzy. V roce 2006 vznikl index PX.",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 13
  },
  {
    "id": 145,
    "topic": "1BP404",
    "question": "Trh BCPP určený od roku 2018 pro malé a střední firmy se jmenuje:",
    "option_a": "Prime Market",
    "option_b": "Free Market",
    "option_c": "Standard Market",
    "option_d": "Start Market",
    "correct": "D",
    "explanation": "Start Market (MTF) je pro malé a střední firmy. Prime a Standard jsou regulovaný trh, Free Market slouží pro zahraniční akcie.",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 13
  },
  {
    "id": 146,
    "topic": "1BP404",
    "question": "Který rys NEODPOVÍDÁ českému trhu cenných papírů?",
    "option_a": "Malý počet kótovaných domácích firem",
    "option_b": "Koncentrace na energetiku a banky (ČEZ, Erste, KB)",
    "option_c": "Vysoká likvidita a desítky IPO ročně",
    "option_d": "Historická zátěž kupónové privatizace a tunelování",
    "correct": "C",
    "explanation": "Český trh je malý, koncentrovaný a málo likvidní, s malým počtem IPO. Souvisí to s bankovním modelem financování a historickou nedůvěrou.",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 13
  },
  {
    "id": 147,
    "topic": "1BP404",
    "question": "Které opatření omezuje využívání offshore center k daňovým únikům?",
    "option_a": "Automatická výměna informací OECD (CRS) a americký FATCA",
    "option_b": "Zrušení evidence skutečných majitelů",
    "option_c": "MiFID I",
    "option_d": "Zavedení REIT",
    "correct": "A",
    "explanation": "Tlak na transparentnost: FATCA (2010), CRS (od 2017), evidence skutečných majitelů, minimální daň 15 % pro velké nadnárodní firmy.",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 13
  },
  {
    "id": 148,
    "topic": "1BP404",
    "question": "Index PX Burzy cenných papírů Praha je cenový index. Co z toho plyne?",
    "option_a": "Zahrnuje reinvestované dividendy",
    "option_b": "Nezahrnuje dividendy, a proto podhodnocuje výkonnost českých akcií s vysokými dividendami",
    "option_c": "Obsahuje jen zahraniční akcie",
    "option_d": "Počítá se jen jednou ročně",
    "correct": "B",
    "explanation": "PX je cenový index bez dividend, výkonnost s dividendami ukazuje PX-TR. U českých firem s vysokými dividendami je rozdíl velký.",
    "created_at": "2026-09-24 08:32:29",
    "subtopic": 13
  }
];
